# Generated by Django 4.0.2 on 2022-02-10 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monday_data',
            options={'managed': True},
        ),
    ]
