# Generated by Django 4.0.4 on 2022-04-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MondayData',
            fields=[
                ('task_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('subtasks', models.TextField()),
                ('contributor', models.TextField()),
                ('people', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('timing', models.TextField()),
            ],
            options={
                'db_table': 'monday_data',
                'managed': False,
            },
        ),
    ]
