# Generated by Django 4.0.1 on 2022-02-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_alter_monday_data_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='modified_Data_Monday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('subtasks', models.TextField()),
                ('contributor', models.TextField()),
                ('status', models.TextField()),
                ('timing', models.TextField()),
                ('ref', models.TextField()),
                ('workStatus', models.BooleanField()),
            ],
            options={
                'managed': True,
            },
        ),
    ]
