# Generated by Django 4.0.4 on 2022-05-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_mondaydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainData',
            fields=[
                ('task_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('subtasks', models.TextField()),
                ('contributor', models.TextField()),
                ('people', models.TextField()),
                ('status', models.TextField(blank=True, null=True)),
                ('timing', models.DateField(blank=True, null=True)),
                ('textworker', models.TextField(blank=True, db_column='textWorker', null=True)),
                ('donebyworker', models.IntegerField(blank=True, db_column='doneByWorker', null=True)),
                ('donebyleader', models.IntegerField(blank=True, db_column='doneByLeader', null=True)),
            ],
            options={
                'db_table': 'main_data',
                'managed': False,
            },
        ),
    ]
