# Generated by Django 4.0.4 on 2022-05-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_maindata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maindata',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mondaydata',
            options={'managed': True},
        ),
    ]
