# Generated by Django 4.0.2 on 2022-02-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_modifiedmondaydata_mondaydata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modifiedmondaydata',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mondaydata',
            options={'managed': True},
        ),
    ]
