# Generated by Django 4.0.1 on 2022-02-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_maindata_alter_modifiedmondaydata_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModifiedMondayData',
        ),
    ]
